name: test
main: MangoTheDev/test/
version: 1.0.0
api: 3.9.0
load: POSTWORLD
author: MangoTheDev
description: test plugin
commands:
  coda:
    permission: coda.command
permissions:
  coda.command:
    default: op
...
